### ISSUE TITLE
Flag "security" not implemented

### ISSUE THREAD

**Issue by pitfallincode** [keilerkonzept/dockerfile-json#18]
Hello,

I found that flag "security" for RUN command is not recognized. I would like to catch option like "insecure" in that flag.
I use version 1.0.8.
You can reproduce the issue with "RUN --security=insecure some_command"
https://docs.docker.com/engine/reference/builder/#run---security

Regards,

**Comment by mckern** [comment]
I took a quick look at this for my own needs, and it looks like this is a shortcoming in https://github.com/moby/buildkit, not in `dockerfile-json`; the error being raised is coming [directly from buildkit](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/parser/parser.go#L169-L181). For my own needs, this is something I'll be keeping an eye on but I don't know that there's much that can be done with `dockerfile-json`.

**Comment by sgreben** [comment]
Thanks @mckern, you are right.

**Comment by sgreben** [comment]
Actually, we just have to build buildkit with the `dfrunsecurity` build tag. I'll add this.

**Comment by sgreben** [comment]
Fixed in [v1.1.0] via #136 :)
