### ISSUE TITLE
Flag value not available for flag mount and network

### ISSUE THREAD

**Issue by pitfallincode** [keilerkonzept/dockerfile-json#19]
Hello,

I found that flags are available, but without the flag values.

for example "RUN --network=host ..." FlagsUsed is set to "network" but flag value "host" is not set.

Same problem with --mount flag.

https://docs.docker.com/engine/reference/builder/#run---mount

Regards

**Comment by sgreben** [comment]
sorry this took forever to address @pitfallincode. I've been quite swamped these days..
